// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {site} from '../models';

export function AddFolder():Promise<string>;

export function ClearCache(arg1:string):Promise<void>;

export function Open(arg1:string):Promise<void>;

export function Publish(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<void>;

export function SetHosting(arg1:string,arg2:boolean):Promise<void>;

export function SetLive(arg1:string,arg2:boolean):Promise<void>;

export function SetPaused(arg1:boolean):Promise<void>;

export function SetSettings(arg1:site.Settings):Promise<void>;

export function Status():Promise<site.Status>;

export function Stop(arg1:string):Promise<void>;
