// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder() {
  return window['go']['main']['App']['AddFolder']();
}

export function ClearCache(arg1) {
  return window['go']['main']['App']['ClearCache'](arg1);
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function Publish(arg1) {
  return window['go']['main']['App']['Publish'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2);
}

export function SetHosting(arg1, arg2) {
  return window['go']['main']['App']['SetHosting'](arg1, arg2);
}

export function SetLive(arg1, arg2) {
  return window['go']['main']['App']['SetLive'](arg1, arg2);
}

export function SetPaused(arg1) {
  return window['go']['main']['App']['SetPaused'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}
